version: '3'
services:
 my-app:
     image: public.ecr.aws/w4j0e6a3/my-app:1.0
     ports:
         - 3000:3000
     restart: always
     depends_on:
         - mongodb
 mongodb:
     image: mongo
     ports:
         - 27017:27017
     environment:
         - MONGO_INITDB_ROOT_USERNAME=admin
         - MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd
     restart: always
     volumes:
         - mongodb-data:/data/db
 mongo-express:
     image: mongo-express
     ports:
         - 8081:8081
     environment:
         - ME_CONFIG_MONGODB_SERVER=mongodb
         - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
         - ME_CONFIG_MONGODB_ADMINPASSWORD=P@ssw0rd
     restart: always
     depends_on:
         - mongodb
volumes:
 mongodb-data:
     driver: local            

